name: Docs
on:
  push:
    branches:
      # https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/
      - $default_branch

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=20 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - run: ./script/publish-docs
        env:
          OCTOKITBOT_PAT: ${{ secrets.OCTOKITBOT_PAT }}
